sonar.projectKey=meal-mate
sonar.projectName=Meal-Mate
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src/test
sonar.test.inclusions=src/test/**/*.test.ts,src/test/**/*.test.tsx
sonar.exclusions=**/*.d.ts,**/node_modules/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
